package main

import (
	htmltpl "html/template"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// factionGroup is one section of the contact sheet.
type factionGroup struct {
	Key    string
	Name   string
	Glyphs []renderedGlyph
}

// factionDisplay maps catalog faction keys to display names. Ships with no
// faction are grouped under "Unaligned".
var factionDisplay = map[string]string{
	"crimson":  "Crimson Fleet",
	"nebula":   "Nebula Federation",
	"solarian": "Solarian Confederacy",
	"outerrim": "Outer Rim",
	"voidborn": "Voidborn Collective",
	"pirate":   "Pirate",
	"":         "Unaligned",
}

// factionOrder fixes section ordering so regenerating produces clean diffs.
var factionOrder = []string{"crimson", "nebula", "solarian", "outerrim", "voidborn", "pirate", ""}

// groupByFaction buckets glyphs into ordered sections, sorting ships within a
// section by class then name so the layout is stable across runs.
func groupByFaction(glyphs []renderedGlyph) []factionGroup {
	buckets := map[string][]renderedGlyph{}
	for _, g := range glyphs {
		buckets[g.Stats.Faction] = append(buckets[g.Stats.Faction], g)
	}

	// Any faction key not in factionOrder is appended alphabetically, so a
	// new faction in the catalog still renders.
	order := slices.Clone(factionOrder)
	var extra []string
	for k := range buckets {
		if !slices.Contains(order, k) {
			extra = append(extra, k)
		}
	}
	slices.Sort(extra)
	order = append(order, extra...)

	var out []factionGroup
	for _, key := range order {
		items := buckets[key]
		if len(items) == 0 {
			continue
		}
		slices.SortFunc(items, func(a, b renderedGlyph) int {
			if c := strings.Compare(a.Stats.Class, b.Stats.Class); c != 0 {
				return c
			}
			return strings.Compare(a.Stats.Name, b.Stats.Name)
		})
		name, ok := factionDisplay[key]
		if !ok || name == "" {
			name = key
		}
		out = append(out, factionGroup{Key: key, Name: name, Glyphs: items})
	}
	return out
}

// contactSheetTmpl renders the whole page. Ship names go through the template's
// automatic escaping; SVG markup is marked trusted because it is built entirely
// from literals and formatted numbers by pkg/shipglyph.
var contactSheetTmpl = htmltpl.Must(htmltpl.New("contactsheet").Funcs(htmltpl.FuncMap{
	"svg": func(s string) htmltpl.HTML { return htmltpl.HTML(s) }, //nolint:gosec // generated by pkg/shipglyph from literals
}).Parse(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Ship Glyph Contact Sheet</title>
<link rel="stylesheet" href="../../smui.css">
<link rel="stylesheet" href="glyphs.css">
</head>
<body>
<header class="site-header">
  <nav class="breadcrumb"><a href="../../index.html">KB</a> / <a href="../index.html">Ships</a> / Glyphs</nav>
  <button class="theme-toggle" id="theme-toggle" aria-label="Toggle theme">◐</button>
</header>
<main class="glyph-sheet">
<h1>Ship Glyph Contact Sheet</h1>
<p class="glyph-intro">{{.Total}} ships, grouped by faction. Top-down schematic outlines generated from class archetype, faction design language and slot counts.</p>
{{range .Groups}}
<section class="glyph-group" id="faction-{{.Key}}">
  <h2>{{.Name}} <span class="glyph-count">{{len .Glyphs}}</span></h2>
  <div class="glyph-grid">
  {{range .Glyphs}}
    <figure class="glyph-cell">
      {{svg .SVG}}
      <figcaption><span class="glyph-name">{{.Stats.Name}}</span><span class="glyph-class">{{.Stats.Class}}</span></figcaption>
    </figure>
  {{end}}
  </div>
</section>
{{end}}
</main>
<script>
(function () {
  var toggle = document.getElementById('theme-toggle');
  if (!toggle) return;
  toggle.addEventListener('click', function () {
    var root = document.documentElement;
    root.dataset.theme = root.dataset.theme === 'dark' ? 'light' : 'dark';
  });
})();
</script>
</body>
</html>
`))

// writeContactSheet renders index.html into outDir.
func writeContactSheet(outDir string, glyphs []renderedGlyph) error {
	data := struct {
		Total  int
		Groups []factionGroup
	}{
		Total:  len(glyphs),
		Groups: groupByFaction(glyphs),
	}

	f, err := os.Create(filepath.Join(outDir, "index.html"))
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()

	return contactSheetTmpl.Execute(f, data)
}
