// Progressive layer rendering system (Phase 13).
// Packages the planetary formation pipeline into discrete layers
// that can be applied incrementally, cached, and visualized
// independently for a guided walkthrough UX.
package layers

import (
	"github.com/rsned/spacemolt-kb/pkg/planetgen/cubemap"
	"github.com/rsned/spacemolt-kb/pkg/planetgen/types"
)

// Category groups related layers for UI organization.
type Category string

const (
	CategoryBase        Category = "Base"
	CategoryTectonics   Category = "Tectonics"
	CategoryOceans      Category = "Oceans"
	CategoryControl     Category = "Control"
	CategorySurface     Category = "Surface"
	CategoryClimate     Category = "Climate"
	CategoryColor       Category = "Color"
	CategoryHydrology   Category = "Hydrology"
	CategoryAtmosphere  Category = "Atmosphere"
	CategoryLife        Category = "Life"
)

// Layer is a single stage in the planetary formation pipeline.
//
// Each layer knows:
// - Its identity (ID, name, description)
// - Which layers it depends on (topological ordering)
// - Which profile parameters it touches (dirty tracking)
// - When it's enabled (conditional layers like civ)
// - How to render itself (heightmap modification)
// - How to render a debug visualization (tectonic preview)
type Layer interface {
	// ID is a stable identifier used for registry lookup and
	// dependency declaration. Must be unique across all layers.
	// Examples: "flat", "plates", "crust", "tectonic-fx", "erosion".
	ID() string

	// Name is the human-readable display name shown in the UI layer list.
	// Should be concise: "Tectonic Plates", "Continental Crust", "Erosion".
	Name() string

	// Description is a brief (1-2 sentence) explanation of what this
	// layer does, shown in the UI corner when the layer is selected.
	// Should explain the geological/process concept at a high level.
	Description() string

	// Category groups related layers for UI organization and filtering.
	// Users can toggle whole categories on/off or filter the layer list.
	Category() Category

	// DependsOn returns the layer IDs that must run before this one.
	// The layer stack validates dependencies and topologically sorts.
	// Empty slice means this layer only depends on layer 0 (flat 0.5).
	// Examples: "crust" depends on ["plates"], "civ" depends on ["rivers", "rain-shadow"].
	DependsOn() []string

	// Params returns the profile field paths this layer touches.
	// Used for:
	// - Extracting template defaults per planet type
	// - Dirty tracking: changing a param marks its layer dirty
	// Format is dot-notation: "Crust.MajorPlates", "Ridged.Amp".
	Params() []string

	// Enabled returns whether this layer is active for the given profile.
	// Some layers are conditional:
	// - Civ: only when profile.Civ.Tier > 0
	// - Erosion: only when profile.Erosion.Droplets > 0
	// - Clouds: only when profile.Cloud.Coverage > 0
	// Disabled layers are skipped during rendering but remain in the stack.
	Enabled(profile *types.PlanetProfile) bool

	// Render applies this layer to the heightmap and returns the updated version.
	// The input heightmap must not be modified; return a new CubeMapF if needed.
	// Context provides seed, size, and cached intermediate fields.
	// Return the same heightmap if this layer has no effect (e.g., disabled).
	Render(ctx *Context, hm *cubemap.CubeMapF) *cubemap.CubeMapF

	// RenderDebug returns a visualization suitable for the tectonic preview.
	// Only meaningful for tectonic-related layers (plates, crust, tectonic-fx);
	// others return nil. The debug render shows:
	// - Plates: colored by plate ID with boundary lines
	// - Crust: continental mask overlay
	// - TectonicFX: boundary classification (belt/subd/arc/ridge/rift colors)
	RenderDebug(ctx *Context) *cubemap.CubeMap
}

// Context holds shared state across layer renders.
//
// Fields are populated lazily as layers request them. Plates, Crust,
// and TectonicFX are pre-computed for the tectonic preview; other
// fields (Flow, ClimateT, ClimateM, RainShadow) are generated by
// their respective layers and cached for downstream consumers.
type Context struct {
	MasterSeed int64
	Size       int  // cube face size (1024, 512, 256, etc.)
	RadiusKm   float64

	// Profile snapshot (immutable for a render pass).
	// Layers must not modify the profile; treat as read-only.
	Profile *types.PlanetProfile

	// Cached intermediate fields.
	// Populated by layers as needed and retained for downstream layers.
	Plates     *PlateField
	Crust      *CrustField
	TectonicFX *TectonicFXField
	Jitter     *JitterField
	Flow       *FlowField
	ClimateT   *cubemap.CubeMapF // temperature field for biomes
	ClimateM   *cubemap.CubeMapF // humidity field for biomes
	RainShadow *RainShadowField
}

// PlateField is a placeholder for the actual field.PlateField.
// TODO: Import from pkg/planetgen/field once integrated.
type PlateField struct{}

// CrustField is a placeholder for the actual field.CrustField.
type CrustField struct{}

// TectonicFXField is a placeholder for the actual field.TectonicFXField.
type TectonicFXField struct{}

// JitterField is a placeholder for the actual noise.JitterField.
type JitterField struct{}

// FlowField is a placeholder for the actual field.FlowField.
type FlowField struct{}

// RainShadowField is a placeholder for the actual biome.RainShadowField.
type RainShadowField struct{}

// registry is the global layer registry.
// Layers self-register via Register() in their init() functions.
var registry = make(map[string]Layer)

// Register adds a layer to the global registry.
// Panics if a layer with the same ID is already registered.
// Called from layer init() functions:
//
//	func init() {
//	    layers.Register(&CrustLayer{})
//	}
func Register(l Layer) {
	id := l.ID()
	if _, exists := registry[id]; exists {
		panic("layer already registered: " + id)
	}
	registry[id] = l
}

// Get retrieves a layer by ID.
// Returns nil if the layer is not registered.
func Get(id string) Layer {
	return registry[id]
}

// All returns all registered layers in dependency order.
// Uses topological sort based on DependsOn() relationships.
// Panics if a cycle is detected.
func All() []Layer {
	// Build adjacency list
	inDegree := make(map[string]int)
	adj := make(map[string][]string) // id -> dependents
	for id, layer := range registry {
		inDegree[id] = 0
		for _, dep := range layer.DependsOn() {
			if _, exists := registry[dep]; !exists {
				panic("unknown dependency: " + dep + " for layer " + id)
			}
			adj[dep] = append(adj[dep], id)
			inDegree[id]++
		}
	}

	// Kahn's algorithm
	var queue []string
	for id, deg := range inDegree {
		if deg == 0 {
			queue = append(queue, id)
		}
	}

	var ordered []Layer
	for len(queue) > 0 {
		id := queue[0]
		queue = queue[1:]
		ordered = append(ordered, registry[id])

		for _, dep := range adj[id] {
			inDegree[dep]--
			if inDegree[dep] == 0 {
				queue = append(queue, dep)
			}
		}
	}

	if len(ordered) != len(registry) {
		panic("cycle detected in layer dependencies")
	}

	return ordered
}

// ByCategory returns all layers in a given category, in dependency order.
func ByCategory(cat Category) []Layer {
	var result []Layer
	for _, layer := range All() {
		if layer.Category() == cat {
			result = append(result, layer)
		}
	}
	return result
}
